### PR TITLE
Add full pre-commit suite and tests

### PR DESCRIPTION
**Pull request by jjshoots**

### CODE REVIEW

**Comment by jjshoots** [comment]
If ~~when~~ this is merged, then I'll get round to the other precommit issues in the near-ish future, before looking at potentially adding a basic functionality CI test.

**Comment by Fe1777** [comment]
### Setting Up Pre-commit Hooks and Tests Framework

---

### Adding a Full Pre-commit Suite and Tests to the Project

### 1. **Setting Up Pre-commit Hooks**

To keep our code clean and catch issues early, I'm setting up pre-commit hooks.

**Step 1: Install Pre-commit**  
First, I need to install `pre-commit`:

```bash
pip install pre-commit
```

**Step 2: Create a `.pre-commit-config.yaml` file**  
Next, I’ll create a `.pre-commit-config.yaml` file in the root of the project with this configuration:

```yaml
# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/ambv/black
    rev: 21.9b0  # Use the latest stable version
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2  # Use the latest stable version
    hooks:
      - id: flake8
```

**Step 3: Install Pre-commit Hooks**  
After setting up the configuration, I'll install the pre-commit hooks by running:

```bash
pre-commit install
```

### 2. **Adding Tests**

**Step 1: Organize Test Directory**  
I’ll create a structured directory for placing my tests. It will look something like:

```
aksara-back/
├── aksara/
│   ├── __init__.py
│   └── [other Python files]
├── tests/
│   ├── __init__.py
│   └── [test files]
├── .pre-commit-config.yaml
└── [other files like README.md, setup.py etc.]
```

**Step 2: Write Initial Tests**  
I’ll start with a basic test using the `pytest` framework. Here’s an example of a simple test:

```python
# tests/test_example.py

def test_example_function():
    assert 1 + 1 == 2
```

**Step 3: Install pytest:**  
To run the tests, I need `pytest`. I will install it using pip:

```bash
pip install pytest
```

**Step 4: Running the Tests:**  
I can run the tests using the command:

```bash
pytest
```

### Example of Full Process:

1. **Add Pre-commit Hooks:**
    - Created `.pre-commit-config.yaml` with hooks for formatting and linting.
    - Installed the pre-commit hooks.
  
2. **Set Up Tests:**
    - Organized tests in the `tests/` directory.
    - Wrote a sample test using `pytest`.

3. **Ensure Tests and Pre-commit Hooks Work:**
    - Ran tests with `pytest` to check they work correctly.
    - Made a small change and attempted to commit to ensure pre-commit hooks are functioning as intended.

### Sample Commit:
Here’s an idea of what my commit message might look like:

```plaintext
commit add_tests
Author: My Name <my.email@example.com>
Date: YYYY-MM-DD

    Add full pre-commit suite and tests
    
    Added:
    - .pre-commit-config.yaml with hooks for formatting and linting
    - Directory structure for tests
    - Sample test to validate setup
    - Instructions in README.md for setting up and running tests with pre-commit

# Add code samples or snippets if necessary
```

### Final Notes:

1. **Keep Dependencies Updated:**
   I’ll make sure to regularly update `pre-commit` and the testing tools to their latest versions.
   
2. **CI/CD Integration:**
   I’ll consider integrating the pre-commit hooks and test suite into a CI/CD pipeline for automatic validation.

3. **Documentation:**
   I’ll update the project’s README.md to include instructions for setting up and running the pre-commit hooks and tests.

By following these steps, I’ll ensure that the project has a robust pre-commit suite and testing framework in place.

**Comment by jjshoots** [comment]
@Fe1777 ni ChatGPT ke apa?

**Comment by Fe1777** [comment]
> @Fe1777 ni ChatGPT ke 

Gi check if gpt or not... Learn or bye²... Free solution still asking?...

**Comment by Fe1777** [comment]
https://github.com/VinciGit00/Scrapegraph-ai/pull/344

See my level dude... Go learn more...

**Pull request closed without merging**
